### PR TITLE
Add recipes for research consumption

### LINKED ISSUE #53: Add a recipe for research consumption
A developer of Pyanodons, Kingarthur1991, would like to have a pseudo-recipe to calculate the research pack consumption in a lab. The recipe is expected to account for the research speed and the productivity buffs.

Original quote:
> Off the top of my head a nice feature would be able to have a fake recipe for calculating science pack consumption in the labs. 
With the milestones and things it should be possible to have it at least show what aware of lab speed and allow for module effects

### PR DESCRIPTION
**Pull request by DaleStan**
This closes #53 and allows you to add technologies to the production table, which produce a new research unit special item.

You can add raw technologies by ctrl-clicking one of the two "Add raw recipe" buttons, or add the research item just like any other product.

For example, you can ask questions like "How much research can I do with lots of prod modules and four (yellow) belts of iron?"
image
or you can do any sort of question involving fixed numbers of labs or a particular number of research units per unit time.

There are also new settings, analogous to the mining productivity setting, for research speed and research productivity.

### CODE REVIEW

**Comment by have-fun-was-taken** [comment]
> There are also new settings, analogous to the mining productivity setting, for research speed and research productivity.

Could you please elaborate on that? 
1. How does one apply the global productivity buff to miners? 
2. How does one apply the global speed and productivity buff to research?

**Comment by DaleStan** [comment]
At the bottom of the auto modules window are (now) three settings for those three bonuses:
image

Is that where they should go? Probably not, but I didn't think about that at the time. Should I move them to the the preferences page?

**Review by veger — COMMENTED** [review]
I 'just' started with pY and I do not have modules available, so I am not very knowledgeable on this topic...

Shouldn't I be able to insert modules in the Lab?
image

**Comment by veger** [comment]
Very cool feature, I have played a little with it and it is quite valuable I see (I didn't know I needed this, but now I do have some use cases :smile: )

**Comment by DaleStan** [comment]
> Shouldn't I be able to insert modules in the Lab?

As far as I can tell, no. The lab doesn't have module slots in-game either. It does accept bonuses from the Vatbrains ("Hidden beacon" in YAFC) and the AM/FM beacons.

**Comment by veger** [comment]
Ah ok... as said I am not even near modules so I never paid attention. Sorry for the noise

**Comment by have-fun-was-taken** [comment]
> Should I move them to the the preferences page?

I'll need to think about it.

**Comment by have-fun-was-taken** [comment]
> I'll need to think about it.

Here are my thoughts:
The goal of #53 is to help the development of pY without compromising the user-experience of pY players. I think the current location of the research-multipliers fits these criteria. 

The only thing that I would like to add to this PR is to change the [name of module settings](https://github.com/have-fun-was-taken/yafc-ce/blob/master/Yafc/Workspace/ProductionTable/ProductionTableView.cs#L614) from "More settings" to "Module settings" for the sake of clarity.

The next steps for this feature in regards of pY would be to set the lab modules to Vatbrain Cartridges with the corresponding bonuses. This way, a player wouldn't have to alter global multipliers every time they would want to see how the numbers change. I've made https://github.com/have-fun-was-taken/yafc-ce/issues/189 about it.

Again @DaleStan, thank you so much for the features! That's a titanic amount of work.

**Review by have-fun-was-taken — APPROVED** [review]

**Comment by have-fun-was-taken** [comment]
Rebased on the fresh master before the merge.

**Pull request merged**
