### PR TITLE
Separate and organize build scripts

### PR DESCRIPTION
**Pull request by have-fun-was-taken**
I got tired of building all distributions when I need only one, so I made separate build-scripts for each target platform.

### CODE REVIEW

**Comment by have-fun-was-taken** [comment]
aaaaaaaaaand it doesn't work because `cd Build` doesn't work from a new location.

**Comment by have-fun-was-taken** [comment]
Is there a more elegant solution than doing the equivalent of `cd ../../` at the start of each script?

**Comment by veger** [comment]
I suppose you could do
```
dotnet publish ../../../YAFC/YAFC.csproj <rest of command>
```
?

Same ugly stuff, just moved :disappointed: 

Alternatively is to run
```
./BuildScripts/sh scripts/build_Linux.sh
```

BTW Using spaces in filenames is (often) asking for problems, or at the least it is annoying. (I usually use `-` instead)

**Comment by have-fun-was-taken** [comment]
> Using spaces in filenames is (often) asking for problems

True. Will fix.

**Comment by veger** [comment]
> I got tired of building all distributions when I need only one

Why/When are you building all distribution when you only need one? To test/run YAFC you can use the `dotnet run` command, and it will build and run from code. For Linux I have to add some library path and end up with `LD_LIBRARY_PATH=$(pwd)/YAFC/lib/linux dotnet run --project ./YAFC/YAFC.csproj` to run.

**Comment by have-fun-was-taken** [comment]
> Why/When are you building all distribution when you only need one?

Now that I thought about it, a custom `dotnet publish` is better than separating build scripts, then running one of them, and using only the resulting folder.

**Pull request closed without merging**
