### PR TITLE
Save window size in preferences

### PR DESCRIPTION
**Pull request by DaleStan**
#162 motivated me to finish this feature: Yafc will now remember the size of the window and whether or not it was maximized, and use that same state the next time you run the application.

### CODE REVIEW

**Review by veger — APPROVED** [review]
Nice addition!

_Edit_ You forgot add an entry the changelog.txt

**Comment by have-fun-was-taken** [comment]
Thank you for your contribution!

I see the following things that can be improved.
* Please resolve the merge conflict. It appeared after I merged #162 
* Please get rid of the merge commit [82e8214](https://github.com/have-fun-was-taken/yafc-ce/pull/166/commits/82e82144e870a231d3f9f3804325cc9c68e4cf39) if possible.
* Please add an entry to the changelog.

**Comment by have-fun-was-taken** [comment]
Aaaallllrighty, I screwed up the rebase, now I need to unscrew it. Working on that.

**Comment by have-fun-was-taken** [comment]
For the record, the command that I used was `git rebase -i 8c549b22^` when at the head of [DaleStan:save-window-size-in-preferences](https://github.com/DaleStan/yafc/tree/save-window-size-in-preferences) with `git commit --allow-empty` for `9fba647... Rebuild the full UI when the window is resized. (#163)`.

**Comment by have-fun-was-taken** [comment]
Okay, screw it. I'll update the branch to the current master, and then cherry-pick the needed commit on top.

**Comment by veger** [comment]
In order to rebase a branch on top for another branch (the `master` branch in this case), I always use `git rebase --ont=master <first commit of the feature branch>^`

Git then rebases all commits from `<first commit>` to `HEAD` on top of `master.

This can still be done if you know the original `<first commit>`. Which I happen to know, as I ahve it locally checked out: 5a57e50f408a04d2cffa6dde8a0cd53ae07a3903

So a `git rebase --onto=master 5a57e50f408a04d2cffa6dde8a0cd53ae07a3903^` should fix all.

**Review by veger — DISMISSED** [review]

**Comment by have-fun-was-taken** [comment]
> I tried and indeed it fixes all

If you did it in Dale's repo, then props to you. From what I saw the master branch in his repo is different from the master of our fork, so I'm not sure if rebasing on top of it would fix stuff. What I did is fetching our master, hard resetting on it for this branch, and then cherry picking the sole commit with the changes.

**Comment by have-fun-was-taken** [comment]
Leaving the part of adding a changelog entry to you guys :D

**Comment by veger** [comment]
I used a `git fetch upstream pull/166/head:<local branch name>` to fetch the branch for this PR. No idea in whose repo it is TBH :wink:

**Review by veger — APPROVED** [review]

**Pull request merged**
