### PR TITLE
Add a checkbox that uses net production instead of gross production for determining which recipes to display.

### PR DESCRIPTION
**Pull request by DaleStan**
For example, with the box checked, Kovarex enrichment ~~will display as [snip previous confusing text]~~ won't show up as a recipe option when attempting to consume U-235, nor when attempting to produce U-238.

I'm not sure we actually want this to be a checkbox, though. Should I make this always on instead?

### CODE REVIEW

**Comment by veger** [comment]
I like to see both consumption and production sides, as it indicates that I need to find some way to start the process (the catalyst). So having this behind a checkbox would be nice (for me at least).

**Review by veger — APPROVED** [review]
Besides the design question, the code looks good to me

**Comment by DaleStan** [comment]
Sounds like a checkbox is the right choice, then. When I'm trying to produce U-238 or consume heavy oil, I don't want YAFC to suggest I add a line for Kovarex enrichment or Coal liquefaction.

**Comment by have-fun-was-taken** [comment]
Updated the branch with a fresh `master`.

**Comment by have-fun-was-taken** [comment]
Regarding the placement of the checkbox, what is the reasoning behind placing it on the welcome screen instead of Preferences? 

My argument for using Preferences is that it's a change of view, when everything in the welcome screen affects the model itself.

The possible counter-argument might be that it's hard to put it in Preferences due to how the model is calculated, but it's just my guess why you implemented it like that.

**Comment by have-fun-was-taken** [comment]
> For example, with the box checked, Kovarex enrichment will display as producing only U-235, and as consuming only U-238.

It seems that it doesn't work.
With and without the net production enabled, the result is the same on vanilla Factorio.
Expected when enabled: With 1/s desired U-235, Kovarex consumes 3/s U-238 and produces 1/s U-235.
Actual result: 40/5 consumed and 41/2 of U-235/U-238 produced.

grafik

Same with the data on hover over the recipe:

grafik

**Comment by have-fun-was-taken** [comment]
On a side note, that's some awesome documentation. Thank you very much!

**Comment by DaleStan** [comment]
Yes, I put it on the Welcome screen because all of the changed code affected by that checkbox happens before the main screen appears. Putting it in the preferences windows is possible, but means duplicating some of the code in `CalculateMaps` (And maybe also in `Dependencies.Calculate()`, since the different links created by `CalculateMaps` create slightly different behavior in the Dependency Explorer.)

> It seems that it doesn't work.
> With and without the net production enabled, the result is the same on vanilla Factorio.

I wasn't clear about what I was changing.
The production table display itself is unchanged. The only intentional UI change is in these dropdowns, where you can select what recipes to add to the tables, and in the lists that appear when you click "Show full list":
image

There's also an unintentional change in the Dependency Explorer, which isn't great:
image
I'm inclined to put U-238 back into the dependents, but if end up moving the checkbox to the preferences it'll fix itself automatically.

**Comment by have-fun-was-taken** [comment]
> The only intentional UI change is in these dropdowns, where you can select what recipes to add to the tables

Can confirm that this change works.

**Review by have-fun-was-taken — APPROVED** [review]
> Putting it in the preferences windows is possible, but means duplicating some of the code.

Since there are reasons for this setting to be on the welcome screen, then we can merge it as-is.

**Pull request merged**
