### PR TITLE
Make pollution cost optional, with setting

### LINKED ISSUE #111: [Discussion] Change CostPerPollution to zero
YAFC [considers](https://github.com/have-fun-was-taken/yafc-ce/blob/master/Yafc.Model/Analysis/CostAnalysis.cs#L22) a recipe more costly if it pollutes more, when I suspect that most of the Pyanodon users play without pollution. 

Therefore, I consider changing the pollution cost to zero. It's not worth it to make it configurable because I think the target audience of YAFC either plays without pollution or doesn't care about it.

What do you guys think?

### PR DESCRIPTION
**Pull request by Dorus**
Setting defaults to off and is stored in project file.

Closes #111

### CODE REVIEW

**Comment by have-fun-was-taken** [comment]
I think if we want it to be a setting, we want it to be a configurable number instead of a boolean switch.

**Comment by Dorus** [comment]
We could do that, but in that case i would think we also want to make a setting out of the other cost parameters

afbeelding

But if we go that route, i would make it a separate dialog, write up some documentation on good defaults, or even add a few pre-selected templates with good default values for different kind of factories.

All of that is quite some work, and out of the scope of what i'm trying to do here.

**Comment by have-fun-was-taken** [comment]
I assume the target audience of your proposed change is the players who want a configurable pollution cost. I'm quite certain that they would want more than a binary choice. 

Please let me know if the target audience is different.

**Comment by Dorus** [comment]
Yeah i would have kept it simple, however changed it to a % input now:

afbeelding

**Comment by have-fun-was-taken** [comment]
> however changed it to a % input now:

Could you please elaborate on why those who care about the pollution part would not want to set it higher than the previous value?

**Comment by Dorus** [comment]
If they care, they can use 200%? 2k%? etc.

I'm not very good with UI so if you have a better proposal or some hint text to add i'm open to it.

**Comment by have-fun-was-taken** [comment]
Ah, you're right. I assumed that 100% was the maximum.

**Comment by have-fun-was-taken** [comment]
Please put the info into the changelog.

**Comment by Dorus** [comment]
@exyi If you have any good proposal on how this should work you could open an issue. Feel free to @ me as this is something I'm interested in working on.

I'd love to hear some thoughts on the list in the screenshot above https://github.com/have-fun-was-taken/yafc-ce/pull/117#issuecomment-2102260820
Would we want to manipulate all those values as they are, have them all 100% on those values? Do we need to be able to modify them all, and all as number or are check boxes ok etc?

**Comment by Dorus** [comment]
Fixed a bunch of spelling errors btw.

**Review by have-fun-was-taken — APPROVED** [review]

**Pull request merged**
