### PR TITLE
Fix potentional NullpointerException

### PR DESCRIPTION
**Pull request by Dorus**
Small fix on previouse code-cleanup.

### CODE REVIEW

**Comment by have-fun-was-taken** [comment]
In the meantime, have you playtested it?

**Comment by Dorus** [comment]
Fair question :-) no. Well i did play around a bit whit the change in my code, but i'm not sure how to his this specific line (if it's possible at all).

**Review by have-fun-was-taken — APPROVED** [review]
Based on what I read about `Task.FromResult`, it probably should not break anything. @veger feel free to merge when you're ready.

**Comment by veger** [comment]
I know that initially I had `return "Summary"` here, which apparently was not correct as I [switched to `return null`](https://github.com/have-fun-was-taken/yafc-ce/commit/3a70d6d2768ef1e01f127cc2a2b6436cf94c3747#diff-cdeaa163e30391ef7d48dda9be6bd4ec764430b1ac7fd65fe1df61a20daf9429R9).
This fixed some issue (it has been over 2 years, so I have no idea about the exact issue, but most likely a wrongly returned type.

I am no C# expert and have no idea what a(n async) Task should return. Back then (and now again), I checked how the result was used and there are/were no situations where the result is directly used without checking whether it is `null` or directly do a comparison without dereferencing. So there should be no possibility for an NPE.

[ProductionTable.Solve()](https://github.com/have-fun-was-taken/yafc-ce/blob/master/YAFCmodel/Model/ProductionTable.cs#L230) returns either a [string or a `null`](https://github.com/have-fun-was-taken/yafc-ce/blob/master/YAFCmodel/Model/ProductionTable.cs#L455) (there are more return paths in this function).

Again, if if is common sense/practice to wrap the `null` in some 'task result' object, then we should do so as well. But then I guess we should fix all `ProjectPageContents` derivatives and return the wrapped result.

**Review by SWeini — APPROVED** [review]

**Comment by Dorus** [comment]
The difference between returning null or returning from Result null is the difference between `solve()` returning `null`, and `await solve()` returning `null`.

Also before the refractor, it was an async method. Those always wrap their result in a `Task` object. 

Thus the code that uses solve `var error = await content.Solve(this);` would look like `await null` after the refractor, while it was `await Task.FromResult<string>(null)` before the refractor, and after my fix.

The refactored code returns a `(Task<string>)null`, while the new one a `(string)null`, (if you await the returned Task).

**Comment by veger** [comment]
Ok, so we have to return the task result, instead of `null` :+1: 

But then we need to fix all `Solve()` functions (they implement an interface, or what the C# terminology for this is). The example I pointed at, is also not wrapping the result of the `Solve()` in a task result.

**Comment by Dorus** [comment]
The one I saw all used async await syntax, when you use that, the compiler will wrap it in a `Task` for you. If they aren't async you would get a type error, except for `null` as that's a valid value both for string and `Task<string>`

**Comment by veger** [comment]
Thanks for the explanation, I learn a lot about C#

Does it make sense to convert this to an async await syntax as well then? So they are all implemented in the same fashion?

**Comment by Dorus** [comment]
You could do so for code style, but it's actually not recommended to make an function async if it doesn't also uses await anywhere. Instead they added `Task.FromResult` for that purpose. The exact details behind that are a bit technical. If I remember correctly it's more efficient.

(there is also this advanced recommendation to split functions in a sync and async part, for example if you can bail out early with some guards. But myself I don't quite like the resulting code style).

**Review by veger — APPROVED** [review]

**Comment by veger** [comment]
Thanks a lot for your patience and providing all this info on async tasks in C# :smile:

**Pull request merged**
