### PR TITLE
Rename folders and namespaces

### PR DESCRIPTION
**Pull request by Dorus**
From https://github.com/have-fun-was-taken/yafc-ce/issues/72#issuecomment-1988934422, https://github.com/have-fun-was-taken/yafc-ce/issues/72#issuecomment-1988940624

<p>
Code style, at least for dotNet projects, suggest you use a single upper case for acronyms if the acronyms is over 2 characters. So YAFCparser should have been YafcParser. (Same for the rest, Yafc, YafcModel, YafcUI etc.)

> The PascalCasing convention, used for all identifiers except parameter names, capitalizes the first character of each word (including acronyms over two letters in length), as shown in the following examples:
> 
> `PropertyDescriptor` `HtmlTag`
>
> A special case is made for two-letter acronyms in which both letters are capitalized, as shown in the following identifier:
> 
> `IOStream`

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers
</p>

I've:
- renamed folders to proper casing
- renamed root namespaces to match new folder names
- renamed YAFCRounding -> YafcRounding

### CODE REVIEW

**Comment by Dorus** [comment]
Yay me, i tried to pull from upstream before i started my work. Apparently i failed to do that correctly and my work is based on week old master.  Will redo :/

**Comment by have-fun-was-taken** [comment]
That's a big change. I think we need to merge it after we fix https://github.com/have-fun-was-taken/yafc-ce/issues/83. Otherwise, it would be adding new changes on top of the critical bug.

**Comment by Dorus** [comment]
I'll subscribe to #83 and will wait for that.

Note this change is quite low risk, but i can understand not wanting to do it if we have any big outstanding work open, since rebase/merge with this might be a little annoying.

**Comment by Dorus** [comment]
I've updated my Pr to the latest master. One change i've made from last time is that i've kept UI as UI now instead of Ui, since i should only have picked acronyms over 2 characters.

**Comment by Dorus** [comment]
One thing i'm especially interested in here for others to test: Does renaming the folders from YAFC to Yafc cause any issues on Linux for existing installs?

**Comment by Dorus** [comment]
Ah, also something goes wrong with loading existing projects. Possibly some conversion needs to be added? TBD.

**Comment by Dorus** [comment]
I've added a quick hack to make it backwards compatible, by renaming the namespace during json parsing. I've also added a version check to this conversion so it's less likely to cause issues later on.

This hack is ugly for 2 reasons:
1. I had to save the entire Project in the context. First we set the project, and then we add the version when we read the rest of the json. This means I cannot set the version directly when the project is added to the context, so i saved the project by reference.
2. This depends on the version to be parsed before we parse the pages. Else the version prop will be `null`. For safety i've set it to always apply the conversion if the version is unknown.

**Comment by have-fun-was-taken** [comment]
While I enjoy fixing the code style, do I understand correctly that the converted save could not be opened in the prevoius versions? If this is so, then this change needs tests. Ideally, including the one where it converts a save-file to a new version.

**Comment by have-fun-was-taken** [comment]
I would also recommend to make a project backup before converting, just in case things go south or a user wants to downgrade.

**Comment by have-fun-was-taken** [comment]
This is a big task. I suggest to approach it as follows:
1. Make a PR with the changes that don't break the save and don't require the conversion.
2. Work on the save-breaking changes and the conversion in a separate PR.

**Comment by Dorus** [comment]
I've already written the code that makes it backwards compatible, that itself wasn't that big of a task (just that i'm not too happy about the implementation, it feels a bit hacky).

Indeed a project backup would be wise (it's wise to always have backups, i have mine stored in google drive so it automatically keeps old versions). However the conversion itself isn't that complex. All you have to do is rename `YAFC.Model.` to `Yafc.Model.` (and the other way around to get back to the previous version). Or if you want to be fancy, `"contentType": "YAFC.Model.` -> `"contentType": "Yafc.Model.`.

Making a PR that doesn't break the project files, would mean keeping the old namespace for a number of classes, or as far as i can tell, these two:
`YAFC.Model.ProductionTable`
`YAFC.Model.Summary`

I'll see if i can keep these two objects in the old namespace for now, and put the save conversion in a separate pr later. It's a bit annoying that we'll be losing compatibility with YaFC this way, so i'll see if there's a way to keep then existing safe format in a cleaner way.

**Comment by Dorus** [comment]
> Make a PR with the changes that don't break the save and don't require the conversion.

I've done this. The second Pr will be a bit more work if that involved adding testcoverage, but it should be a ton smaller.

**Comment by Dorus** [comment]
For reference, the full rename including the save conversion is at https://github.com/Dorus/yafc-ce/tree/rename-save-breaking

**Comment by veger** [comment]
> One thing i'm especially interested in here for others to test: Does renaming the folders from YAFC to Yafc cause any issues on Linux for existing installs?

Most likely not. Linux (indeed) has case-sensitive filenames, ~but assuming all references are fixed (automatically) as well, it should not pose an issue.~

_Edit_ I was curious so I tried. But it failed due to some naming issue of the UI project:
> /usr/share/dotnet/sdk/6.0.128/Microsoft.Common.CurrentVersion.targets(2068,5): warning : The referenced project '../Yafc.UI/Yafc.UI.csproj' does not exist. [/home/user/yafc/Yafc.Model/Yafc.Model.csproj]

Followed by a whole bunch of related errors were classes could not be found.

The folder is called `Yafc.Ui` and the solution has `Yafc.UI` as a reference. This case-sensitive related difference is most likely causing the breakage.

By renaming the folder and the csproj file, YAFC starts again.

But now I lost my config (dark theme is white, and most recent project settings are gone)
I see that the config is not stored in `~/.local/share/Yafc` instead of `~/.local/share/YAFC`.

I didn't check further than this.

**Comment by Dorus** [comment]
Thanks for checking! This is the typical disaster i was afraid of. When you work with git on windows, it doesn't always register capital renaming, and you need to go ui -> UI2 -> UI and do `git add` twice. Locally all files had to correct name (i double checked that), but in git it was off in a few places.

Should all be fixed now, if you're willing to check again :)

**Comment by Dorus** [comment]
> I see that the config is not stored in ~/.local/share/Yafc instead of ~/.local/share/YAFC.

Ah yes, this was the other thing i wasn't sure about. I think i'll reverse the config folder name chance, there isn't much reason do do that change and it'll be a headache on Linux i think. (if we do it, we can do it as part of the other namespace conversion pr)

**Comment by veger** [comment]
It now seems to be working fine on Linux

**Comment by veger** [comment]
I think this is ready to be merged, right @have-fun-was-taken?

**Review by have-fun-was-taken — APPROVED** [review]
Works on Windows too

**Review by have-fun-was-taken — APPROVED** [review]
Fixed merge confilicts. From now on, I'll do them in merge commits instead of rebasing, for clarity.

**Comment by Dorus** [comment]
In my experience rebase makes it easier to do future rebases, but indeed if you're about to merge it, a merge commit makes sense.

**Pull request merged**
